FROM openjdk:11-jre-slim as loader
ADD  ./target/RawDataImporter-jar-with-dependencies.jar .

## old importer
#ENTRYPOINT ["java", "-Xmx8192m", "-jar", "RawDataImporter-jar-with-dependencies.jar"]
#CMD [ "/local/source/" ]"

#
ENTRYPOINT ["java", "-Xmx8192m", "-jar", "DictionaryImporterUtil-jar-with-dependencies.jar"]